#!/bin/sh
#SBATCH --chdir=./
#SBATCH --job-name=Depth_species
#SBATCH --nodes=1 --ntasks=2
#SBATCH --partition=quanah
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=8G

. ~/conda/etc/profile.d/conda.sh
conda activate samtools

# Set working directory
workdir=?

# Calculate the depth of coverage per site
samtools depth -a ${workdir}/01_bam/species_final.bam > ${workdir}/Depth/species_depth.txt

# Isolate the third column with the read counts only to reduce file size
cut -f3 ${workdir}/Depth/species_depth.txt > ${workdir}/Depth/species_depth_reduced.txt

# Remove the full depth file
rm ${workdir}/Depth/species_depth.txt
